
source 'https://github.com/componentizationdemo/PXModulSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'PXXibPersonKit_Example' do
  pod 'PXXibPersonKit', :path => '../'
  pod 'PXPersonInfoCatogeryKit'
  pod 'PXPersonInfoKit'
  pod 'PXPersonPrefenceKit'
  pod 'PXPersonPrefrenceCatogeryKit'
  target 'PXXibPersonKit_Tests' do
    inherit! :search_paths

    
  end
end
